apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-workbench-faststream-validator-stage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: no-workbench-faststream-validator
  template:
    metadata:
      labels:
        app: no-workbench-faststream-validator
    spec:
      containers:
        - name: no-workbench-validator
          image: 568130295144.dkr.ecr.ap-south-1.amazonaws.com/ondc-prod-prod-ondc-images:ondc-no-workbench-validations-v6
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "b-3.kafkaonsearchcluster.u3k9qd.c2.kafka.ap-south-1.amazonaws.com:9092"
            - name: KAFKA_CONSUMER_TOPIC
              value: "on_search_cluster_p2p_payload"
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "no-workbench-staging-validator-group"
            - name: DOMAIN_TO_VALIDATE
              value: "ONDC:RET10,ONDC:RET11"
            - name: KAFKA_VALIDATIONS_SUCCESS_TOPIC
              value: "no_workbench_staging_validations_done"
            - name: KAFKA_VALIDATIONS_MISSING_TOPIC
              value: "no_workbench_staging_validations_missing"
            - name: KAFKA_MAX_POLL_RECORDS
              value: "1"
            - name: KAFKA_MAX_POLL_INTERVAL_MS
              value: "120000"
            - name: KAFKA_HEARTBEAT_INTERVAL_MS
              value: "3000"
            - name: KAFKA_SESSION_TIMEOUT_MS
              value: "30000"
          resources:
            requests:
              memory: "500Mi"
              cpu: 1000m
            limits:
              memory: "2Gi"
              cpu: 2000m
          